robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: ['waist', 'shoulder', 'elbow', 'wrist_yaw']
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

