robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: ['waist', 'shoulder', 'elbow', 'wrist_yaw', 'wrist_pitch']
  gains:
   waist: {p: 10000.0, i: 0.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
   shoulder: {p: 10000.0, i: 0.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
   elbow: {p: 10000.0, i: 0.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
   wrist_yaw: {p: 10000.0, i: 0.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
   wrist_pitch: {p: 10000.0, i: 0.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}

gripper_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: ['gripper_joint']
  
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

