robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: ['waist', 'shoulder', 'elbow', 'wrist_yaw', 'wrist_pitch']

gripper_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: ['gripper_joint', "l_finger_2_joint", "l_finger_passive_joint", "r_finger_1_joint", "r_finger_passive_joint"]

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

