# REMOVA O NÓ RAIZ "tangs:" PARA CARREGAR NO NAMESPACE CORRETO
# Controlador de estados das juntas (obrigatório)
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Controladores de posição (ajuste os nomes das juntas com o tf_prefix!)
waist_position_controller:
  type: effort_controllers/JointPositionController
  joint: waist  # Nome da junta com prefixo
  pid: {p: 150.0, i: 0.0, d: 0.0}

shoulder_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder  # Nome da junta com prefixo
  pid: {p: 200.0, i: 1.0, d: 0.0}

elbow_position_controller:
  type: effort_controllers/JointPositionController
  joint: elbow  # Nome da junta com prefixo
  pid: {p: 10.0, i: 50.0, d: 0.15}

wrist_yaw_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_yaw  # Nome da junta com prefixo
  pid: {p: 200.0, i: 50.0, d: 0.0}

wrist_pitch_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_pitch  # Nome da junta com prefixo
  pid: {p: 300.0, i: 1.0, d: 0.0}

gripper_position_controller:
  type: effort_controllers/JointPositionController
  joint: gripper_joint  # Nome da junta com prefixo
  pid: {p: 20.0, i: 10.0, d: 0.06}