joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

arm_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - waist
    - shoulder
    - elbow
    - wrist_yaw
    - wrist_pitch
  gains:
    waist: {p: 100.0, d: 0.1, i: 1.0, i_clamp: 1.0}
    shoulder: {p: 100.0, d: 0.1, i: 1.0, i_clamp: 1.0}
    elbow: {p: 100.0, d: 0.1, i: 1.0, i_clamp: 1.0}
    wrist_yaw: {p: 100.0, d: 0.1, i: 1.0, i_clamp: 1.0}
    wrist_pitch: {p: 100.0, d: 0.1, i: 1.0, i_clamp: 1.0}

