joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# Controladores do braço robotico
arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - waist
    - shoulder
    - elbow
    - wrist_yaw
  gains:
    waist: {p: 150.0, i: 0.0, d: 0.0}
    shoulder: {p: 200.0, i: 1.0, d: 0.0}
    elbow: {p: 10.0, i: 50.0, d: 0.15}
    wrist_yaw: {p: 200.0, i: 50.0, d: 0.0}
    

# Controlador do gripper
gripper_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - gripper_joint
  gains:
      gripper_joint: {p: 1.0, i: 1.0, d: 0.0}