controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - tangs/waist
      - tangs/shoulder
      - tangs/elbow
      - tangs/wrist_yaw
      - tangs/wrist_pitch
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - tangs/gripper_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: start
  - group: gripper
    pose: close