controller_list:
  - name: tangs/robot_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
    - tangs/waist
    - tangs/shoulder
    - tangs/elbow
    - tangs/wrist_yaw
    - tangs/wrist_pitch
  
  - name: tangs/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    paralell: true
    joints:
    - tangs/gripper_joint
      

  
  